modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "GPLv3"

[[mods]]
modId = "heart_crystals"
version = "${version}"
displayName = "Heart Crystals"
authors = "n643064"
description = '''
Adds Heart Crystals, which increase player health when consumed
'''
logoFile = "icon.png"

[[dependencies.heart_crystals]]
modId = "neoforge"
mandatory = true
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.heart_crystals]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"
